-- Asset Redemption System
-- Enables users to redeem asset codes (permanent tiers, consumable tokens)
-- with identity-blind double-redemption prevention via HMAC receipt keys

-- Redemption Codes Table
-- Generated by admin/payment system, redeemed by users
CREATE TABLE IF NOT EXISTS redemption_codes (
  -- Unique ID (ULID)
  id TEXT PRIMARY KEY,
  
  -- Redemption code (format: XXXX-XXXX-XXXX-XXXX)
  code TEXT NOT NULL UNIQUE,
  
  -- Asset type: permanent (one-time unlock) or consumable (replenishable balance)
  type TEXT NOT NULL CHECK (type IN ('permanent', 'consumable')),
  
  -- Specific asset type identifier (e.g., 'pro_tier', 'ai_tokens')
  asset_type TEXT NOT NULL,
  
  -- Value/balance for consumable assets (null for permanent)
  value INTEGER,
  
  -- Metadata: tier details, limits, description, etc.
  metadata JSONB NOT NULL DEFAULT '{}',
  
  -- Current status
  status TEXT NOT NULL CHECK (status IN ('active', 'redeemed', 'revoked', 'expired')) DEFAULT 'active',
  
  -- When created
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Expiration date (optional, null = never expires)
  expires_at TIMESTAMPTZ,
  
  -- When code was redeemed
  redeemed_at TIMESTAMPTZ,
  
  -- Failed redemption attempt count (for rate limiting)
  failed_attempts INTEGER NOT NULL DEFAULT 0
);

-- Index for fast code lookup during redemption
CREATE INDEX IF NOT EXISTS redemption_codes_code_idx 
  ON redemption_codes(code);

-- Index for filtering by status
CREATE INDEX IF NOT EXISTS redemption_codes_status_idx 
  ON redemption_codes(status);

-- Redemption Receipts Table
-- Identity-blind double-redemption prevention
-- receiptKey = HMAC(identityFingerprint + codeId, SERVER_SECRET)
-- Server stores HMAC without storing identity, achieving:
-- - Double-redemption prevention (can check if receipt exists)
-- - Identity privacy (can't reverse HMAC to find identity)
CREATE TABLE IF NOT EXISTS redemption_receipts (
  -- Unique ID (ULID)
  id TEXT PRIMARY KEY,
  
  -- HMAC-based receipt key for identity-blind tracking
  -- Computed as: HMAC-SHA256(fingerprint + codeId, REDEMPTION_RECEIPT_SECRET)
  receipt_key TEXT NOT NULL UNIQUE,
  
  -- FK to redemption code
  code_id TEXT NOT NULL REFERENCES redemption_codes(id) ON DELETE CASCADE,
  
  -- When redeemed
  redeemed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Unique index on receipt_key (enforces double-redemption prevention)
CREATE UNIQUE INDEX IF NOT EXISTS redemption_receipts_receipt_key_idx 
  ON redemption_receipts(receipt_key);

-- Index for querying by code (to see all redemptions of a code)
CREATE INDEX IF NOT EXISTS redemption_receipts_code_id_idx 
  ON redemption_receipts(code_id);

-- Table comments
COMMENT ON TABLE redemption_codes IS 'Asset codes that can be redeemed by users for permanent tiers or consumable tokens';
COMMENT ON TABLE redemption_receipts IS 'Identity-blind redemption tracking using HMAC receipt keys to prevent double-redemption while preserving privacy';

-- Column comments
COMMENT ON COLUMN redemption_codes.code IS 'Redemption code format: XXXX-XXXX-XXXX-XXXX';
COMMENT ON COLUMN redemption_codes.type IS 'permanent: one-time unlock | consumable: replenishable balance';
COMMENT ON COLUMN redemption_codes.asset_type IS 'Specific asset identifier: pro_tier, ai_tokens, etc.';
COMMENT ON COLUMN redemption_codes.value IS 'Balance for consumable assets (null for permanent)';
COMMENT ON COLUMN redemption_codes.metadata IS 'Additional asset details: tier limits, description, etc.';
COMMENT ON COLUMN redemption_codes.status IS 'active: can be redeemed | redeemed: already used | revoked: invalidated | expired: past expiration date';
COMMENT ON COLUMN redemption_codes.failed_attempts IS 'Failed redemption attempt count (for rate limiting and fraud detection)';

COMMENT ON COLUMN redemption_receipts.receipt_key IS 'HMAC-SHA256(fingerprint + codeId, SECRET) - enables double-redemption prevention without storing identity';
COMMENT ON COLUMN redemption_receipts.code_id IS 'Reference to redeemed code';
